### ISSUE TITLE
KEES tech tree concerns

### ISSUE THREAD

**Issue by Volkkeslate** [N3h3miah/OrbitalMaterialScience#81]
While testing this i put my primary concerns into seeing how the progression of unlocking the tech in this mod progressed. That being said, I'm a bit concerned as to how useful the KEES experiments unlocked in survivability actually are. Sure they are easy enough to get up into orbit with the supplied container but the problem that arises is that at such an early state in career you are unable to EVA in space unless you fork out 70,000 funds for an upgrade to your astronaut center. While it is an important upgrade it can really strap you for cash that early on. The alternate solution to not having EVA is to send them up on the experiment racks, but that doesn't work due to the inbuilt 2G restrictions. (yes it is possible to get them into orbit but have fun getting them back down while reentry at 4-5G's. The parachute deployment alone will snap them off since it hits 10 G's in stock and around 8 with FAR and realchute installed)

Another concern with the same experiment is the amount of time it takes to run the experiment. Without batteries unlocked in the "Science Tech" node i was required to make 2-3 rather long burns to keep enough electrical charge to not end up with a dead capsule that was nonreturnable.

I feel there may need to be some balancing or these experiments need to be bumped higher into the tech tree. Perhaps bridging the gap with smaller versions that may not give as much science, some of the Gemini 4 experiments come to mind. http://en.wikipedia.org/wiki/Gemini_4#Experiments

**Comment by N3h3miah** [comment]
Then Alpha 2 will be for you. The new labs and experiments in 0.6 Alpha 2 resulted in some moving around of parts in the tech tree. Feedback on this is welcome.

I'm aware that the parts in general are placed early in the tech tree. The electric charge requirement is a good point, that one actually slipped my mind. Your suggestion sparked an idea, since we are using Module Manager for other parts why not add the ability to store and run a simple experiment to the command pod. This new research program, call it "Kemini" (better name suggestions are always welcome) could start as early as Basic Rocketry, as it should be possible for the average player to reach orbit in this level. This would allow for even earlier science and to push some of the other part higher in the tech tree.

**Comment by N3h3miah** [comment]
I finished the Kemini research program implementation. I guess it solves this problem. If you disagree reopen it.
